### PR TITLE
Replace lerna with pnpm

### PR DESCRIPTION
**Pull request by qm3ster**
This allows for much faster CI and local builds

Also added `jest` to travis

Tests are currently failing, but fixed in PR #31

Also fixed eslint config not to have implicit dependencies
and irrelevant plugins, eg: browser compatibility and flowtype

### CODE REVIEW

**Comment by amilajack** [comment]
Hey @qm3ster. I'm somewhat reluctant on using pnpm because I haven't used it with my own projects that much. Lerna seems to be a much more standard when it comes to monorepo management. Can you help me understand what using pnpm gives us that we don't already have?

**Comment by qm3ster** [comment]
Well for me, pnpm is its own reward, because of its speed and "strictness" (no transient dependencies).
And since this repo isn't a set of packages that are meant for release, the things missing from pure pnpm (bumping versions, publishing) don't matter here.
For repos that do need releasing, I have recently deployed `@microsoft/rush`, and I am very pleased with it. The default there is also `pnpm`, but they do support `npm` and `yarn` as well.

**Comment by theJian** [comment]
@qm3ster Does it require users to install `pnpm` before they can run examples? I think we should have the minimal prerequisites so newcomers can get started as quick as possible.

**Comment by qm3ster** [comment]
@theJian It does not. The users can, just as before, `cd` to a specific example's package directory and `yarn` or `npm i` it alone.

**Pull request closed without merging**
