### PR TITLE
Fix #51 ; Make it more understandable: primitives

### LINKED ISSUE #51: Make it more understandable: primitives
`primitives` is not very kind for beginers who need the examples. This idea is to better more:

1. Split the `fn primitives` for each [JS primitive types](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures)
2. Call the all of splitted functions from `lib/index.js` with printing then it will be show 7 ( or 6 ) types/lines.
3. Append an useful link to the souce code commenting about [JS primitive types](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures) for helpful.

Workflow:

1. [x] Approval by the authors and colaborators
2. [x] Modifying
3. [x] PR & Merge

-----

related #50

### PR DESCRIPTION
**Pull request by usagi**
- Complete the task #51
- Update the dependencies

Fixes #51

### CODE REVIEW

**Review by amilajack — CHANGES_REQUESTED** [review]
Don't git ignore the lockfile

**Comment by usagi** [comment]
Well, it is not an essential fixing, so let's accept it unconditionally.

**Comment by usagi** [comment]
I'll check it once, but do you @amilajack really want "yarn.lock"? If "yes" then I'll commit the lock file into the `fixup` commit.

image

**Comment by amilajack** [comment]
See this blog post from yarn's blog: https://classic.yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

**Comment by usagi** [comment]
I understood the opinion of yarn and the this repos policy for the `yarn.lock`! Thanks. I'll `fixup` soon.

**Comment by amilajack** [comment]
It's interesting how this PR doesn't have its CI tests running. Can you try rebasing this branch against master.

**Comment by usagi** [comment]
@amilajack I do not know the CI settings of this repos, but I will make time for `rebase` later.

**Review by amilajack — CHANGES_REQUESTED** [review]
Waiting on rebase

**Comment by usagi** [comment]
Hmm, I'll close it and remake the PR. I don't know how to re-run the CI. Ughhhhhh

**Pull request closed without merging**
